services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Pluswerk\MailLogger\:
    resource: '../Classes'
    exclude:
      - '../Classes/Logging/LoggingTransport.php'
      - '../Classes/Dto/'

  Pluswerk\MailLogger\Domain\Model\:
    resource: '../Classes/Domain/Model/*'
    shared: false

  TYPO3\CMS\Core\Mail\MailerInterface:
    alias: Pluswerk\MailLogger\Logging\MailerExtender
  TYPO3\CMS\Core\Mail\Mailer:
    alias: Pluswerk\MailLogger\Logging\MailerExtender

  Pluswerk\MailLogger\Command\TestMailCommand:
    tags:
      - name: 'console.command'
        command: 'maillogger:testmail'
        description: 'This command sends a mail with your complete setup and logs it. Additionally you can provide a mail template key and test your template in the default language, of course without variables.'
        schedulable: false
